from config.settings import Config

COURSES_TABLE = f'''
create table if not exists courses
(
    id             integer generated by default as identity
        constraint courses_pk
            primary key,
    name           text,
    last_price     double precision,
    best_bid_price double precision,
    best_ask_price double precision,
    created_at     timestamp
);

alter table courses
    owner to {Config.PSQL_DB_USER};
'''